;; (setq smtpmail-smtp-server "localhost")
;; (setq smtpmail-smtp-service 1025)
;; (setq "MAILHOST" "localhost")
;; (setq rmail-primary-inbox-list '("po:sboling")
;;       rmail-pop-password-required t)
